### ISSUE TITLE
Align issue labels with pioneer XP

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer.github.io#17]
In consultation with @nicolaiparlog : Align the website labels to the labels of the extension pack.

And if too bored: similar colors for label groups, like all status blue, all types red etc. (in xp too)

**Comment by Bukama** [comment]
I transferred most of the XP labels to website, but adjusted some of them to (hopefully) fit better for the website project. 

I also adjusted the colors of the labels (also in XP where you get an better impression as there are more [labeled issues](https://github.com/junit-pioneer/junit-pioneer/issues)). 

I tried to:
* use soft colors (but without any scientific background - I'm quite sure that there may be some accessibility problems for color blind people - but I hope that they are not too bad)
* use different colors per group
* use same color for each label of a group, with three exceptions to highlight those: `type: bug`, `status: in-progress`, `status: blocked`
* use a green, highlighting color for the label "up for grabs"

**Comment by aepfli** [comment]
cool, i think this looks great, although i would put a little bit more nuances into theme and type - at first glance they look like the same to me :D

**Comment by aepfli** [comment]
type theme and component

**Comment by NPException** [comment]
Another possibility to show the differences between labels aside from colour would be to accentuate the label groups (and the three exceptions separately). Though that would require finding well fitting icons for each group, which is probably just as hard as naming things in code. 😅 

possible examples:

- **💼 theme: xyz**
- **🚦 status: xyz**
- **🐞type: bug**

**Comment by Bukama** [comment]
Thanks for the feedback. To get further feedback I updated the labels **but only here in webpage repo**:

* Changed `up-for-grabs` to  `up-for-grabs / good first issue` and `status: won't fix` to `status: won't fix / don't do` 
* Updated colors to (hopefully) achieve a better distinction
* Added emojis to each category

To get a glance, check the [issue site](https://github.com/junit-pioneer/junit-pioneer.github.io/issues)

Now better? Any colors to aggressive?

**Comment by nipafx** [comment]
I like the more saturated colors and the emojis, but I think they would have an even better effect if prepended to the category instead of appended.

**Comment by Bukama** [comment]
Updated
