### ISSUE TITLE
Github Action to manually trigger site build

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer.github.io#18]
Since a few weeks GitHub Actions can be triggered via a manual action, e.g. a button  etc.

We want this to start the site build and release.
Only maintainers should be allowed to trigger the build.

**Comment by aepfli** [comment]
added, and fixed build 
![image](https://user-images.githubusercontent.com/9987394/89328248-60bdb680-d68d-11ea-9f52-8500dcc1379a.png)

**Comment by aepfli** [comment]
@Bukama as i experienced some strange issues, which were related to a misconfiguration of the pages, i needed to work around in the grandmaster branch, and did not create a PR. Hence that i suggest to close this issue, any objections? if not, please just close it

**Comment by nipafx** [comment]
Thank you @aepfli, that is pretty cool! I will now go ahead and make live harder for everyone by squashing all your commits into a single one. :blush:
