### ISSUE TITLE
Unreadable docs of Clearing or Setting System Properties / Environment Variables

### ISSUE THREAD

**Issue by TWiStErRob** [junit-pioneer/junit-pioneer.github.io#35]
https://junit-pioneer.org/docs/environment-variables

![image](https://user-images.githubusercontent.com/2906988/214842824-57df3849-74ae-4e1e-8075-3d5ef88df4a7.png)

**Comment by Bukama** [comment]
Thank you for pointing this out to us!
Even it's a website issue I leave it here where the individual docs source is located. If it turns out the problem is in the website itself I'll transfer it.

It seems to only affect Clearing or Setting System Properties / Environment Variables

**Comment by TWiStErRob** [comment]
No, it's all of them.

**Comment by TWiStErRob** [comment]
I haven't inspected it yet.

**Comment by aepfli** [comment]
https://github.com/junit-pioneer/junit-pioneer.github.io/blob/2ede0d4ac02db739d19b72ccf49f53e9dc323416/_includes/page__hero.html#L30-L34

Those lines are creating this content - we would need to check if this is related to either a wrong excerpt or tagline definition or something generating this as such. Maybe the idea was that the first sentence of the documentation should be a short and precise oneliner, and somehow this should have been noticed. eg. for the Cartesian product, it is just `From Wikipedia` in the first paragraph.

Anyhow thank you for the nice catch, we will look deeper into it, and will propose a solution :) Most likely, either change the first sentence of the docs or adapt the layout. (my opinion)

**Comment by TWiStErRob** [comment]
I don't think it matters if it's one word, or a whole paragraph, dark text on dark background is like &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.
That way of extracting a headline is common practice, so the text is fine.

The problem is that the whole website is dark, and the body color / header is overridden to be light, but the default text color is still dark, because

https://github.com/junit-pioneer/junit-pioneer.github.io/blob/2ede0d4ac02db739d19b72ccf49f53e9dc323416/_config.yml#L15

To use a dark website you need to change the value of the above to `dark`, as described in the [docs](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin) and customize the colors from there.

@nipafx might have more context if this ever worked, or broke.

**Comment by nipafx** [comment]
This was a bug in the website, the text was not supposed to be there since it's just the first paragraph. See b2f5e11 for details.
