### ISSUE TITLE
 Move Site Build to GitHub Actions

### ISSUE THREAD

**Issue by nipafx** [junit-pioneer/junit-pioneer.github.io#5]
The site build is currently not executed after a successful project build because [triggering it fails](https://travis-ci.org/github/junit-pioneer/junit-pioneer/jobs/667429711?utm_medium=notification&utm_source=github_status):

> Triggering Travis build failed. Response{protocol=http/1.1, code=403, message=Forbidden, url=https://api.travis-ci.org/repo/junit-pioneer%2Fjunit-pioneer.github.io/requests}

Since we're moving XP to GitHub Actions (see junit-pioneer/junit-pioneer#192), we should do the same here.

**Comment by aepfli** [comment]
So lets outline the current build what is going on etc.

1. the build is triggered from remote
2. we set up jekyll
3. we do checkouts 
    - project with different branches
    - junit-pioneer to the working folder
4. we do a gradle to build
5. we copy some files from main repo to site-source folder, so we have the docs, also maybe the main page not sure
6. we adapt the navigation to represent all necessary links from the docs
7. we will than trigger a jekyll build
8. and we commit and push

How can this look like in the future (maybe without gradle and without shell scripts, or shell scripts just for debugging)

1. we trigger the build remotely
2. we checkout the repo itself in site-source branch
    - we check out sub repos with https://github.com/marketplace/actions/checkout (defining path etc)
3. we move files from junit pioneer repo to docs folder
4. we adapt the navigation with https://github.com/marketplace/actions/find-and-replace
5. we trigger the jekyll build via jekyll actions, need to evaluate which one is more suited

voila - the build would work with just one actions file, we could get rid of the grandmaster branch, and would have a clean build

**Comment by nipafx** [comment]
I want to make it as easy as possible to build and publish the site locally. Unless I miss something, replacing Gradle/script logic with GitHub Actions, doesn't allow that. Duplicating logic doesn't seem to be a good idea, either. As such, I will try to "just" replicate the content of `.travis.yml` with GitHub Actions configuration.
