### ISSUE TITLE
Show current version on junit-pioneer.org

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer.github.io#9]
Moved from [junit-pioneer #98](https://github.com/junit-pioneer/junit-pioneer/issues/98) as we decided to move all web site related issues.

@nicolaiparlog wrote:
> It should be easy for visitors to immediately see the latest version they can download.
> 
> A possible implementation would be to query the [Maven Central API](http://search.maven.org/#api) for the most recent version. Another would be to have Shipkit trigger a specific "publication" build that presents the version determined by Shipkit. The latter might be necessary anyway to publish release notes (see https://github.com/junit-pioneer/junit-pioneer/issues/97), which are also only available after Shipkit's commit.

> Heroku badge: ![Latest Junit Pioneer on Maven Central](https://camo.githubusercontent.com/9f57d5c3502b4dff79a42f45152ef19dfcd41dfe/68747470733a2f2f6d6176656e2d6261646765732e6865726f6b756170702e636f6d2f6d6176656e2d63656e7472616c2f6f72672e6a756e69742d70696f6e6565722f6a756e69742d70696f6e6565722f62616467652e7376673f7374796c653d666c6174)
> 
> Shields.io: ![Latest JUnit Pioneer on Maven Central](https://camo.githubusercontent.com/8b6bbf647fbbdfa9a80f1fc8e1ff033cda78e0cf/68747470733a2f2f696d672e736869656c64732e696f2f6d6176656e2d63656e7472616c2f762f6f72672e6a756e69742d70696f6e6565722f6a756e69742d70696f6e6565722e737667)

@sormuras wrote
> Do the colors have a meaning? What controls it?

@nicolaiparlog wrote:
> No. Can't be changed. (Both are guesses.)

**Comment by Bukama** [comment]
@nicolaiparlog is working on that

**Comment by Bukama** [comment]
We came to the conclusion that the labels shown above are not fitting the pages design, so we will read the current version from the versions properties and place them next to the coordinates on the front page.

**Comment by beatngu13** [comment]
Another alternative: You can also query the GitHub API for the latest release:

https://api.github.com/repos/junit-pioneer/junit-pioneer/releases/latest

`tag_name`/`name` contain the version string (e.g. "v0.9.0").

**Comment by Bukama** [comment]
Done on today's stream. Not merged yet.
